// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3AhUjeTJDooYiO3-jj6kZyrdr72H6ML8',
    appId: '1:257725667702:web:0f630251c65b90b31e8257',
    messagingSenderId: '257725667702',
    projectId: 'notelity-flutter',
    authDomain: 'notelity-flutter.firebaseapp.com',
    storageBucket: 'notelity-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVllKf2416vOi-gVlLtDUhjOyrGzRAoL0',
    appId: '1:257725667702:android:218eecc2b6e0e96c1e8257',
    messagingSenderId: '257725667702',
    projectId: 'notelity-flutter',
    storageBucket: 'notelity-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx6NNK3VWJ4fotkMO4-LTUDvna9boRXdQ',
    appId: '1:257725667702:ios:9e873280cad598281e8257',
    messagingSenderId: '257725667702',
    projectId: 'notelity-flutter',
    storageBucket: 'notelity-flutter.firebasestorage.app',
    iosBundleId: 'com.example.notelity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx6NNK3VWJ4fotkMO4-LTUDvna9boRXdQ',
    appId: '1:257725667702:ios:9e873280cad598281e8257',
    messagingSenderId: '257725667702',
    projectId: 'notelity-flutter',
    storageBucket: 'notelity-flutter.firebasestorage.app',
    iosBundleId: 'com.example.notelity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3AhUjeTJDooYiO3-jj6kZyrdr72H6ML8',
    appId: '1:257725667702:web:d3b104e1f2681a961e8257',
    messagingSenderId: '257725667702',
    projectId: 'notelity-flutter',
    authDomain: 'notelity-flutter.firebaseapp.com',
    storageBucket: 'notelity-flutter.firebasestorage.app',
  );
}
